CREATE TABLE `news` (
	`ID` INT(7) UNSIGNED NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(50) NOT NULL,
	`content` TEXT NOT NULL,
	`slug` VARCHAR(50) NOT NULL,
	`time_create` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`time_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`image_name` VARCHAR(50) NULL DEFAULT NULL,
	`category` TINYINT(4) NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `ID` (`ID`),
	UNIQUE INDEX `slug` (`slug`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=25
;
